### ISSUE TITLE
Already in Dev check fail

### ISSUE THREAD

**Issue by troyBORG** [wimpysworld/rolling-rhino#11]
I installed the from the latest daily build, and ran your script.
It on Ubuntu, and then did an apt update and apt upgrade check.  
And noticed it didn't show it was on devel.  So I ran your script again and I got errors:

https://paste.ubuntu.com/p/4CZbqY7Dt6/

**Comment by troyBORG** [comment]
Testing again, with a clean install of Xubuntu, this time I can't even install.  
I get the same errors:

`troyborg@troyborg-UBRolling:~/rolling-rhino$ sudo ./rolling-rhino 
Rolling Rhino 🦏
  [+] INFO: lsb_release detected.
  [+] INFO: Ubuntu detected.
  [+] INFO: Ubuntu Groovy Gorilla (development branch) detected.
  [+] INFO: Detected xubuntu-desktop.
  [+] INFO: No PPAs detected, this is good.
  [+] INFO: All checks passed.
Are you sure you want to start tracking the devel series? [Y/N]Y./rolling-rhino: line 115: EOM: No such file or directory
./rolling-rhino: line 118: deb: command not found
./rolling-rhino: line 123: deb: command not found
./rolling-rhino: line 129: deb: command not found
./rolling-rhino: line 131: deb: command not found
./rolling-rhino: line 139: deb: command not found
./rolling-rhino: line 141: deb: command not found
./rolling-rhino: line 149: deb: command not found
./rolling-rhino: line 159: deb: command not found
./rolling-rhino: line 161: deb: command not found
./rolling-rhino: line 163: deb: command not found
./rolling-rhino: line 165: EOM: command not found
  [+] INFO: Switching to devel series.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Get:1 http://us.archive.ubuntu.com/ubuntu groovy InRelease [267 kB]
Hit:2 http://security.ubuntu.com/ubuntu groovy-security InRelease                     
Hit:3 http://us.archive.ubuntu.com/ubuntu groovy-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu groovy-backports InRelease
Fetched 267 kB in 6s (44.5 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
troyborg@troyborg-UBRolling:~/rolling-rhino$`

**Comment by leroyshirto** [comment]
This looks like an issue around the heredoc. I'll take a look at it
