### ISSUE TITLE
Question - Devel Security?

### ISSUE THREAD

**Issue by Lucapz** [wimpysworld/rolling-rhino#13]
https://wiki.ubuntu.com/SecurityTeam/ReleaseCycle

> post-beta

    focus security updates on any updates still missing from devel release that are present in stable updates (see 'Show all out-of-sync CVEs for the devel release' from $UCT/README for assistance) 

Does this mean that running rolling-rhino could be less secure than the point release?

Is the Devel security policy any different to the point release for open/closed ports or changes in running services as i wouldn't want things enabled by default that would normally be disabled in the point release?

If that made any sense :)

Thanks

**Comment by basak** [comment]
There are a few reasons security updates can be delayed in the development release versus in the stable releases. An example recent in my memory: a spurious QA false positive can hold the update in the development proposed pocket while developers fix the false positive, whereas in the stable releases the priority is to land the security update.

**Comment by flexiondotorg** [comment]
@Lucapz The answer from @basak is accurate, as he is an archive admin for Ubuntu. I'll close this as the question is answered.

**Comment by Lucapz** [comment]
But what about open ports and running services is it the same between the point release and Devel?
