### ISSUE TITLE
how to back to previous release

### ISSUE THREAD

**Issue by Zelda00** [wimpysworld/rolling-rhino#20]
Hi
good job. Your idea is very easy to use convert the distribution from long support to rolling distribution, through the executable file (sh).
Only the thing that I hope to amend it and add it in the executable file! It is the optional return method (y/n) from a rolling distribution to a previous distribution, because most users will find it difficult to return after the experiment.
Thanks for the hard work

**Comment by elcste** [comment]
> Your idea is very easy to use convert the distribution from long support to rolling distribution,

This tool doesn't support that exactly. You need to start from a daily build image, as per the README (emphasis added):

> Rolling Rhino is a simple tool to convert Ubuntu Desktop, and the official desktop flavours, that has been *installed from a daily image* into a "rolling release"

**Comment by Zelda00** [comment]
> This tool doesn't support that exactly. You need to start from a daily build image, as per the README (emphasis added):

Thanks for your response, so the way to go back is manual by building the image.
We hope to see new projects for you.
