### ISSUE TITLE
Run inside a bedrock Linux stratum

### ISSUE THREAD

**Issue by Titaniumtown** [wimpysworld/rolling-rhino#33]
Could support be added to run the installation script in a ubuntu stratum?

Thanks!

**Comment by flexiondotorg** [comment]
Sorry, I have no plans to support anything other than official Ubuntu flavours.

**Comment by Titaniumtown** [comment]
It's not an ubuntu flavor, it's still ubuntu but in a chroot, sorta. https://bedrocklinux.org/

It allows you to have multiple distros side by side.
