### ISSUE TITLE
Questions/Stability?

### ISSUE THREAD

**Issue by mister-x123** [wimpysworld/rolling-rhino#38]
Hi sorry if this is posted in the wrong area, as I didn't know where else to post it or ask.
If possible can I please get the questions directly answered. Also I understand how Ubuntu is designed to work, but personally got sick of using PPA's, doing dist-upgrades, etc, hence why I'm here. I've used Arch a ton in the past and decided to try this out.

My 1st question is: How stable is the Ubuntu development branch compared to say Arch packages? Yes I know what I am doing and my way around Linux, I'm asking simply out of curiosity.
2nd question: Is the development branch similar to that of Debian's testing branch (buster/bullseye)? Or is it more comparable to Debian Sid/Unstable?
3rd question: What process/stages do packages go through before they're released on the development branch (if any) - for example: unstable>testing/development>stable/release candidate?
Last question: what packages are recommended to block/freeze from updating if I want a little bit of extra stability?

I'm using it currently on a gaming PC where there isn't really anything of any importance, but I'm genuinely interested with this and before making the switch permanently I'd just like to know the above.
TIA

**Comment by mister-x123** [comment]
Hello? Car 54 where are you? Come in

**Comment by mister-x123** [comment]
....???? Earth to WimpysWorld, come in!

**Comment by ItzSwirlz** [comment]
Patience. Much better appropriate ways to ask for attention, such as just saying "Awaiting response"

**Comment by mister-x123** [comment]
Yeah but after a week of no response to simple questions you can't blame me for being frustrated with the lack of response.
Over it now. Marking it as closed. Given up
